Routes:
- Path: "api/v1/openpositions"
  Callback: "Getallopenpositions"
  Method: "GET"
- Path: "api/v1/openpositions/{id}"
  Callback: "Getopenpositions"
  Method: "GET"
- Path: "api/v1/openpositions"
  Callback: "Createopenpositions"
  Method: "POST"
- Path: "api/v1/openpositions"
  Callback: "Updateopenpositions"
  Method: "PUT"
- Path: "api/v1/openpositions"
  Callback: "Deleteopenpositions"
  Method: "DELETE"
